apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-state-alert.rules
  namespace: openshift-storage
  labels:
    app: rook-ceph
spec:
  groups:
    - name: cluster-state-alert.rules
      rules:
        - alert: CephClusterErrorState
          expr: ceph_health_status{job="rook-ceph-mgr"} >= 1
          for: 1m
          labels:
            severity: critical
            severity_level: error
            storage_type: ceph
          annotations:
            description: Storage cluster is in error state for more than 1m.
            message: Storage cluster is in error state
            runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/CephClusterErrorState.md
