#!/usr/bin/env python3
"""
Merge must-gather analysis XML into JUnit XML before Report Portal upload.

This script:
1. Reads the JUnit XML file generated by pytest
2. Finds test cases with 'must-gather-analysis-url' property
3. Loads the corresponding must-gather analysis XML file
4. Extracts key metrics and adds them as test properties
5. Embeds the full XML content in the test's <system-out> section
6. Writes the modified JUnit XML back to the same file

Usage:
    python merge_must_gather_xml.py <junit_xml_path>
"""

import argparse
import logging
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

try:
    from junitparser import JUnitXml, Properties, Property
except ImportError:
    print("ERROR: junitparser library not found. Install with: pip install junitparser")
    sys.exit(1)

logging.basicConfig(level=logging.INFO, format="%(levelname)s:%(name)s:%(message)s")
logger = logging.getLogger(__name__)

# URL to local path mapping
MAGNA_BASE_URL = "http://magna002.ceph.redhat.com"
MAGNA_MOUNT = "/mnt"


def url_to_local_path(url):
    """Convert Magna URL to local filesystem path."""
    if url.startswith(MAGNA_BASE_URL):
        return url.replace(MAGNA_BASE_URL, MAGNA_MOUNT, 1)
    return url


def extract_must_gather_metrics(xml_content):
    """
    Parse must-gather analysis XML and extract key metrics.

    Returns:
        dict: Key metrics to add as JUnit properties
    """
    try:
        root = ET.fromstring(xml_content)
        metrics = {}

        # Extract deployment summary metrics
        summary = root.find("deployment-summary")
        if summary is not None:
            ceph_health = summary.findtext("ceph-health", "UNKNOWN")
            overall_status = summary.findtext("overall-status", "UNKNOWN")
            metrics["mg-ceph-health"] = ceph_health
            metrics["mg-overall-status"] = overall_status

            # Extract storage cluster phase
            sc_phase = summary.findtext("storagecluster-phase")
            if sc_phase:
                metrics["mg-storagecluster-phase"] = sc_phase

            # Extract noobaa phase
            noobaa_phase = summary.findtext("noobaa-phase")
            if noobaa_phase:
                metrics["mg-noobaa-phase"] = noobaa_phase

        # Extract pod counts
        pods = root.find("pods")
        if pods is not None:
            total = pods.findtext("total")
            failed = pods.findtext("failed")
            if total:
                metrics["mg-pod-total"] = total
            if failed:
                metrics["mg-pod-failed"] = failed

        # Extract operator status
        operators = root.find("operators")
        if operators is not None:
            degraded_count = 0
            for op in operators.findall("operator"):
                degraded = op.findtext("degraded", "false").lower()
                if degraded == "true":
                    degraded_count += 1
            if degraded_count > 0:
                metrics["mg-operators-degraded"] = str(degraded_count)

        logger.debug(f"Extracted metrics: {metrics}")
        return metrics

    except ET.ParseError as e:
        logger.error(f"Failed to parse must-gather XML: {e}")
        return {}
    except Exception as e:
        logger.error(f"Unexpected error extracting metrics: {e}")
        return {}


def merge_must_gather_into_junit(junit_xml_path):
    """
    Merge must-gather analysis XML into JUnit XML file.

    Args:
        junit_xml_path: Path to the JUnit XML file

    Returns:
        int: Number of test cases modified
    """
    if not os.path.exists(junit_xml_path):
        logger.error(f"JUnit XML file not found: {junit_xml_path}")
        return 0

    logger.info(f"Processing JUnit XML: {junit_xml_path}")

    # Load JUnit XML
    try:
        xml = JUnitXml.fromfile(junit_xml_path)
    except Exception as e:
        logger.error(f"Failed to parse JUnit XML: {e}")
        return 0

    modified_count = 0

    # Iterate through all test suites and test cases
    for suite in xml:
        for testcase in suite:
            # Find must-gather-analysis-url property
            mg_url = None
            props = testcase.child(Properties)
            if props:
                for prop in props:
                    if prop.name == "must-gather-analysis-url":
                        mg_url = prop.value
                        break

            if not mg_url:
                continue

            logger.info(f"Found must-gather URL for test: {testcase.name}")

            # Convert URL to local path and derive XML path
            text_path = url_to_local_path(mg_url)
            xml_path = text_path.replace(".txt", ".xml")

            if not os.path.exists(xml_path):
                logger.warning(f"Must-gather XML not found: {xml_path}")
                continue

            logger.info(f"Reading must-gather XML: {xml_path}")

            # Read must-gather XML content
            try:
                with open(xml_path, "r") as f:
                    xml_content = f.read()
            except Exception as e:
                logger.error(f"Failed to read XML file {xml_path}: {e}")
                continue

            # Extract metrics and add as properties
            metrics = extract_must_gather_metrics(xml_content)
            if metrics:
                if not props:
                    props = Properties()
                    testcase.append(props)

                for key, value in metrics.items():
                    prop = Property(name=key, value=value)
                    props.add_property(prop)
                    logger.debug(f"Added property: {key}={value}")

            # Embed full XML in system-out
            separator = "\n" + "=" * 80 + "\n"
            mg_section = (
                f"{separator}"
                f"Must-Gather Analysis XML\n"
                f"{separator}\n"
                f"{xml_content}\n"
                f"{separator}"
            )

            # Append to existing system-out or create new
            if testcase.system_out:
                testcase.system_out += mg_section
            else:
                testcase.system_out = mg_section

            modified_count += 1
            logger.info(f"Merged must-gather XML for test: {testcase.name}")

    if modified_count > 0:
        # Write modified XML back to file
        try:
            xml.write(junit_xml_path)
            logger.info(f"Successfully modified {modified_count} test case(s)")
        except Exception as e:
            logger.error(f"Failed to write JUnit XML: {e}")
            return 0
    else:
        logger.info("No test cases with must-gather analysis found")

    return modified_count


def main():
    parser = argparse.ArgumentParser(
        description="Merge must-gather analysis XML into JUnit XML for Report Portal"
    )
    parser.add_argument("junit_xml", help="Path to the JUnit XML file")
    parser.add_argument("--debug", action="store_true", help="Enable debug logging")

    args = parser.parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    junit_path = Path(args.junit_xml).resolve()

    try:
        count = merge_must_gather_into_junit(str(junit_path))
        if count > 0:
            logger.info(f"Successfully processed {count} test case(s)")
            return 0
        else:
            logger.warning("No modifications made")
            return 0
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())
