#!/usr/bin/env python3
"""
Merge must-gather analysis text report into JUnit XML before Report Portal upload.

This script:
1. Reads the JUnit XML file generated by pytest
2. Finds test cases with 'must-gather-analysis-url' property
3. Embeds the human-readable text report in the test's <system-out> section
4. Writes the modified JUnit XML back to the same file

Usage:
    python merge_must_gather_report.py <junit_xml_path>
"""

import argparse
import logging
import os
import re
import sys
from pathlib import Path

try:
    from junitparser import JUnitXml, Properties
except ImportError:
    print("ERROR: junitparser library not found. Install with: pip install junitparser")
    sys.exit(1)

logging.basicConfig(level=logging.INFO, format="%(levelname)s:%(name)s:%(message)s")
logger = logging.getLogger(__name__)

# URL to local path mapping
MAGNA_BASE_URL = "http://magna002.ceph.redhat.com"
MAGNA_MOUNT = "/mnt"


def url_to_local_path(url):
    """Convert Magna URL to local filesystem path."""
    if url.startswith(MAGNA_BASE_URL):
        return url.replace(MAGNA_BASE_URL, MAGNA_MOUNT, 1)
    return url


def sanitize_for_xml(text):
    """Strip ANSI escape codes and XML-invalid control characters."""
    text = re.sub(r"\x1b\[[0-9;]*m", "", text)
    # Remove all control chars except tab, newline, carriage return
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", "", text)
    return text


def merge_must_gather_into_junit(junit_xml_path):
    """
    Merge must-gather analysis XML into JUnit XML file.

    Args:
        junit_xml_path: Path to the JUnit XML file

    Returns:
        int: Number of test cases modified
    """
    if not os.path.exists(junit_xml_path):
        logger.error(f"JUnit XML file not found: {junit_xml_path}")
        return 0

    logger.info(f"Processing JUnit XML: {junit_xml_path}")

    # Load JUnit XML
    try:
        xml = JUnitXml.fromfile(junit_xml_path)
    except Exception as e:
        logger.error(f"Failed to parse JUnit XML: {e}")
        return 0

    modified_count = 0

    # Iterate through all test suites and test cases
    for suite in xml:
        for testcase in suite:
            # Find must-gather-analysis-url property
            mg_url = None
            props = testcase.child(Properties)
            if props:
                for prop in props:
                    if prop.name == "must-gather-analysis-url":
                        mg_url = prop.value
                        break

            if not mg_url:
                continue

            logger.info(f"Found must-gather URL for test: {testcase.name}")

            # Convert URL to local path
            text_path = url_to_local_path(mg_url)

            if not os.path.exists(text_path):
                logger.warning(f"Must-gather text report not found: {text_path}")
                continue

            try:
                with open(text_path, "r") as f:
                    text_content = sanitize_for_xml(f.read())
            except Exception as e:
                logger.error(f"Failed to read text file {text_path}: {e}")
                continue

            separator = "\n" + "=" * 80 + "\n"
            mg_section = (
                f"{separator}"
                f"Must-Gather Analysis Report\n"
                f"{separator}\n"
                f"{text_content}\n"
                f"{separator}"
            )

            # Append to existing system-out or create new
            if testcase.system_out:
                testcase.system_out += mg_section
            else:
                testcase.system_out = mg_section

            modified_count += 1
            logger.info(f"Merged must-gather report for test: {testcase.name}")

    if modified_count > 0:
        # Write modified XML back to file
        try:
            xml.write(junit_xml_path)
            logger.info(f"Successfully modified {modified_count} test case(s)")
        except Exception as e:
            logger.error(f"Failed to write JUnit XML: {e}")
            return 0
    else:
        logger.info("No test cases with must-gather analysis found")

    return modified_count


def main():
    parser = argparse.ArgumentParser(
        description="Merge must-gather analysis XML into JUnit XML for Report Portal"
    )
    parser.add_argument("junit_xml", help="Path to the JUnit XML file")
    parser.add_argument("--debug", action="store_true", help="Enable debug logging")

    args = parser.parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    junit_path = Path(args.junit_xml).resolve()

    try:
        count = merge_must_gather_into_junit(str(junit_path))
        if count > 0:
            logger.info(f"Successfully processed {count} test case(s)")
            return 0
        else:
            logger.warning("No modifications made")
            return 0
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    sys.exit(main())
