#!/usr/bin/env python3
"""
JIRA text helpers + legacy entry point.

Repro steps and tests are generated by Claude (see verification-generation-prompt.md),
not by hardcoded scenarios in this module.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

from jira_client import adf_to_text as adf_text

__all__ = [
    "extract_jira_context",
    "extract_numbered_steps",
    "extract_fix_snippet",
]


FIX_SNIPPET_RE = re.compile(
    r"await\s+require\([^)]+\)[^;]*load_root_keys_from_mount\(\)[^;]*;?",
    re.IGNORECASE,
)


def extract_fix_snippet(desc: str) -> str:
    m = FIX_SNIPPET_RE.search(desc)
    return m.group(0).strip() if m else ""


_SECTION_STOP = re.compile(
    r"^(actual results|expected results|logs collected|additional info|"
    r"the exact date|can this issue|is there any workaround)",
    re.IGNORECASE,
)


def extract_numbered_steps(description: str) -> list[dict]:
    steps: list[dict] = []
    if not description:
        return steps
    section = description
    m = re.search(
        r"steps\s+to\s+reproduce:?\s*(.*)",
        description,
        re.IGNORECASE | re.DOTALL,
    )
    if m:
        section = m.group(1)
    for line in section.splitlines():
        line = line.strip()
        if not line or _SECTION_STOP.match(line):
            if _SECTION_STOP.match(line):
                break
            continue
        num = re.match(r"^(\d+)[.)]\s+(.+)$", line)
        if not num:
            continue
        content = num.group(2).strip()
        if not content or content in (".", "-") or len(content) > 240:
            continue
        steps.append({"action": f"jira_step_{num.group(1)}", "details": content})
    return steps


def extract_jira_context(
    raw: dict | None, *, target_release_field: str = "customfield_10886",
) -> dict[str, Any]:
    ctx: dict[str, Any] = {
        "linked_issues": [],
        "comment_snippets": [],
        "fix_versions": [],
        "affects_versions": [],
        "target_release": None,
        "components": [],
        "assignee": None,
    }
    if not raw:
        return ctx
    fields = raw.get("fields") or {}
    for link in fields.get("issuelinks") or []:
        for side in ("inwardIssue", "outwardIssue"):
            issue = link.get(side)
            if not issue:
                continue
            ctx["linked_issues"].append(
                {
                    "key": issue.get("key"),
                    "summary": (issue.get("fields") or {}).get("summary"),
                    "status": ((issue.get("fields") or {}).get("status") or {}).get(
                        "name"
                    ),
                    "relation": (link.get("type") or {}).get("name"),
                }
            )
    for c in (fields.get("comment") or {}).get("comments") or []:
        body = c.get("body")
        text = adf_text(body) if isinstance(body, dict) else str(body or "")
        if text.strip():
            ctx["comment_snippets"].append(
                {
                    "author": (c.get("author") or {}).get("displayName"),
                    "text": text.strip()[:500],
                }
            )
    for fv in fields.get("fixVersions") or []:
        if fv.get("name"):
            ctx["fix_versions"].append(fv["name"])
    for av in fields.get("versions") or []:
        if av.get("name"):
            ctx["affects_versions"].append(av["name"])
    tr = fields.get(target_release_field)
    if isinstance(tr, dict) and tr.get("name"):
        ctx["target_release"] = tr["name"]
    for comp in fields.get("components") or []:
        if comp.get("name"):
            ctx["components"].append(comp["name"])
    assignee = fields.get("assignee")
    if isinstance(assignee, dict):
        ctx["assignee"] = assignee.get("displayName")
    return ctx


def main() -> None:
    print(
        "build_repro_steps.py: use build_repro_context.py + Claude verification-generation-prompt.md",
        file=sys.stderr,
    )
    parser = argparse.ArgumentParser()
    parser.add_argument("--issue", required=True)
    parser.add_argument("--art", type=Path, required=True)
    parser.add_argument("--odf-version", default="")
    args = parser.parse_args()
    # Delegate to context builder
    import build_repro_context as brc

    sys.argv = [
        "build_repro_context.py",
        "--issue",
        args.issue,
        "--art",
        str(args.art),
        "--odf-version",
        args.odf_version,
    ]
    brc.main()


if __name__ == "__main__":
    main()
