#!/usr/bin/env python3
"""Extract JIRA facts for AI-driven repro/script generation (no hardcoded scenarios).

This module owns two phases:
  1. enrich()        — jira-raw.json  →  analysis.json
  2. build_context() — analysis.json + jira-raw.json  →  repro-context.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml as _yaml

from jira_client import adf_to_text as adf_text
from build_repro_steps import (
    extract_fix_snippet,
    extract_jira_context,
    extract_numbered_steps,
)

_POLICY_PATH = Path(__file__).resolve().parents[1] / "configs" / "policies" / "safety.yaml"


def _blocked_labels() -> list[str]:
    if _POLICY_PATH.is_file():
        with _POLICY_PATH.open() as f:
            policy = _yaml.safe_load(f) or {}
        return policy.get("blocked_labels_skip", [])
    return ["skip-ocsci-agent"]


# ---------------------------------------------------------------------------
# Phase 1 — enrich (was enrich_analysis.py)
# ---------------------------------------------------------------------------

def enrich(raw: dict, *, issue_key: str) -> dict:
    """Build an ``analysis.json`` dict from a raw JIRA issue payload."""
    fields = raw.get("fields") or {}
    desc = fields.get("description")
    text = adf_text(desc) if isinstance(desc, dict) else str(desc or "")
    labels = fields.get("labels") or []
    blocked = any(lbl in labels for lbl in _blocked_labels())
    ctx = extract_jira_context(raw)
    fix = extract_fix_snippet(text)

    return {
        "issue_key": issue_key,
        "summary": fields.get("summary"),
        "status": (fields.get("status") or {}).get("name"),
        "labels": labels,
        "description_excerpt": text[:8000],
        "fix_snippets": [fix] if fix else [],
        "jira_target_release": ctx.get("target_release"),
        "jira_components": ctx.get("components", []),
        "linked_issues": ctx.get("linked_issues", []),
        "feasible": not blocked,
        "skipped_by_label": blocked,
        "confidence": 0.0 if blocked else 0.5,
        "ai_generation_required": True,
        "root_cause_summary": None,
        "expected_behavior": None,
        "verification_strategy": None,
        "note": "Interpretation and test plan come from Claude via verification-generation-prompt.md",
    }


# ---------------------------------------------------------------------------
# Phase 2 — build_context
# ---------------------------------------------------------------------------


def build_context(
    analysis: dict, raw: dict | None, *, issue_key: str, odf_target: str
) -> dict[str, Any]:
    desc = analysis.get("description_excerpt") or ""
    if raw:
        fields = raw.get("fields") or {}
        d = fields.get("description")
        if isinstance(d, dict):
            desc = adf_text(d) or desc

    jira_ctx = extract_jira_context(raw)
    numbered = extract_numbered_steps(desc)

    return {
        "issue_key": issue_key,
        "odf_version_target": odf_target,
        "summary": analysis.get("summary"),
        "status": analysis.get("status"),
        "labels": analysis.get("labels", []),
        "root_cause_summary": analysis.get("root_cause_summary"),
        "expected_behavior": analysis.get("expected_behavior"),
        "verification_strategy": analysis.get("verification_strategy"),
        "description_text": desc[:12000],
        "fix_snippets": [s for s in [extract_fix_snippet(desc)] if s],
        "jira_numbered_steps": numbered,
        "jira_linked_issues": jira_ctx.get("linked_issues", []),
        "jira_comments": jira_ctx.get("comment_snippets", []),
        "jira_fix_versions": jira_ctx.get("fix_versions", []),
        "jira_affects_versions": jira_ctx.get("affects_versions", []),
        "jira_target_release": jira_ctx.get("target_release"),
        "jira_components": jira_ctx.get("components", []),
        "gaps": [
            g
            for g, cond in (
                ("numbered_steps_empty_in_jira", not numbered),
                (
                    "analysis_may_be_template_only",
                    "Steps to Reproduce:1.2.3" in desc.replace(" ", ""),
                ),
            )
            if cond
        ],
        "ai_generation_required": True,
        "note": "Repro steps and tests must be generated by Claude from this file — not from hardcoded templates.",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--issue", required=True)
    parser.add_argument("--art", type=Path, required=True)
    parser.add_argument("--odf-version", default="")
    parser.add_argument(
        "--enrich-only",
        action="store_true",
        help="Run only the enrich phase (produce analysis.json) and exit.",
    )
    args = parser.parse_args()

    art = args.art
    issue_key = args.issue.upper()
    analysis_path = art / "analysis.json"

    # --- Phase 1: enrich (if needed or requested) -------------------------
    raw = (
        json.loads((art / "jira-raw.json").read_text())
        if (art / "jira-raw.json").is_file()
        else None
    )

    if not analysis_path.is_file() or args.enrich_only:
        if raw is None:
            raise SystemExit("jira-raw.json not found — cannot enrich")
        plan = enrich(raw, issue_key=issue_key)
        analysis_path.write_text(json.dumps(plan, indent=2) + "\n")
        print("skipped" if plan.get("skipped_by_label") else "ok")
        if args.enrich_only:
            return

    # --- Phase 2: build_context -------------------------------------------
    analysis = json.loads(analysis_path.read_text())

    ctx = build_context(
        analysis,
        raw,
        issue_key=issue_key,
        odf_target=args.odf_version or analysis.get("odf_version", ""),
    )
    out = art / "repro-context.json"
    out.write_text(json.dumps(ctx, indent=2) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
