#!/usr/bin/env python3
"""Extract JIRA facts for AI-driven repro/script generation (no hardcoded scenarios)."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from build_repro_steps import (
    adf_text,
    extract_fix_snippet,
    extract_jira_context,
    extract_numbered_steps,
)


def build_context(
    analysis: dict, raw: dict | None, *, issue_key: str, odf_target: str
) -> dict[str, Any]:
    desc = analysis.get("description_excerpt") or ""
    if raw:
        fields = raw.get("fields") or {}
        d = fields.get("description")
        if isinstance(d, dict):
            desc = adf_text(d) or desc

    jira_ctx = extract_jira_context(raw)
    numbered = extract_numbered_steps(desc)

    return {
        "issue_key": issue_key,
        "odf_version_target": odf_target,
        "summary": analysis.get("summary"),
        "status": analysis.get("status"),
        "labels": analysis.get("labels", []),
        "root_cause_summary": analysis.get("root_cause_summary"),
        "expected_behavior": analysis.get("expected_behavior"),
        "verification_strategy": analysis.get("verification_strategy"),
        "description_text": desc[:12000],
        "fix_snippets": [s for s in [extract_fix_snippet(desc)] if s],
        "jira_numbered_steps": numbered,
        "jira_linked_issues": jira_ctx.get("linked_issues", []),
        "jira_comments": jira_ctx.get("comment_snippets", []),
        "jira_fix_versions": jira_ctx.get("fix_versions", []),
        "jira_affects_versions": jira_ctx.get("affects_versions", []),
        "jira_target_release": jira_ctx.get("target_release"),
        "jira_components": jira_ctx.get("components", []),
        "gaps": [
            g
            for g, cond in (
                ("numbered_steps_empty_in_jira", not numbered),
                (
                    "analysis_may_be_template_only",
                    "Steps to Reproduce:1.2.3" in desc.replace(" ", ""),
                ),
            )
            if cond
        ],
        "ai_generation_required": True,
        "note": "Repro steps and tests must be generated by Claude from this file — not from hardcoded templates.",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--issue", required=True)
    parser.add_argument("--art", type=Path, required=True)
    parser.add_argument("--odf-version", default="")
    args = parser.parse_args()

    art = args.art
    analysis = json.loads((art / "analysis.json").read_text())
    raw = (
        json.loads((art / "jira-raw.json").read_text())
        if (art / "jira-raw.json").is_file()
        else None
    )

    ctx = build_context(
        analysis,
        raw,
        issue_key=args.issue.upper(),
        odf_target=args.odf_version or analysis.get("odf_version", ""),
    )
    out = art / "repro-context.json"
    out.write_text(json.dumps(ctx, indent=2) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
