#!/usr/bin/env bash
# Validate MCP-related env and write workspace/mcp-env.sh for REST discovery fallback.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR/../../.." && pwd)"
WS="${JIRA_AGENT_WORKSPACE:-$ROOT/.claude/workspace}"
EXAMPLE="$ROOT/.claude/configs/mcp/claude-code-mcp.example.json"

mkdir -p "$WS"

MCP_ENV="$WS/mcp-env.sh"

# Source existing mcp-env.sh first so previous credentials persist across runs
if [[ -f "$MCP_ENV" ]]; then
  source "$MCP_ENV"
fi

# Allow TOKEN alias for JIRA_MCP_TOKEN
export JIRA_MCP_TOKEN="${JIRA_MCP_TOKEN:-${TOKEN:-}}"
export JIRA_MCP_URL="${JIRA_MCP_URL:-https://redhat.atlassian.net}"
export JIRA_MCP_EMAIL="${JIRA_MCP_EMAIL:-}"

# Map MCP env → REST discovery env (search_jql.py / discover.sh)
JIRA_URL="${JIRA_URL:-$JIRA_MCP_URL}"
JIRA_EMAIL="${JIRA_EMAIL:-$JIRA_MCP_EMAIL}"
JIRA_API_TOKEN="${JIRA_API_TOKEN:-$JIRA_MCP_TOKEN}"

cat >"$MCP_ENV" <<EOF
# Generated by setup_mcp.sh — source before jira-repro/discovery or REST JIRA calls
export JIRA_MCP_URL="${JIRA_MCP_URL}"
export JIRA_MCP_EMAIL="${JIRA_MCP_EMAIL}"
export JIRA_MCP_TOKEN="${JIRA_MCP_TOKEN}"
export JIRA_URL="${JIRA_URL}"
export JIRA_EMAIL="${JIRA_EMAIL}"
export JIRA_API_TOKEN="${JIRA_API_TOKEN}"
EOF

echo "setup_mcp: wrote $MCP_ENV"

MISSING=0
if [[ -z "$JIRA_MCP_TOKEN" ]]; then
  echo "setup_mcp: JIRA_MCP_TOKEN not set (export TOKEN or JIRA_MCP_TOKEN for REST fallback)" >&2
  MISSING=1
fi
if [[ -z "$JIRA_MCP_EMAIL" ]]; then
  echo "setup_mcp: JIRA_MCP_EMAIL not set (needed for REST fallback)" >&2
  MISSING=1
fi

REST_AVAILABLE=True
if [[ "$MISSING" -eq 1 ]]; then
  REST_AVAILABLE=False
  echo "" >&2
  echo "setup_mcp: WARNING — REST API fallback unavailable (MCP server is the primary path)" >&2
  echo "  To enable REST fallback for terminal-only discovery, set:" >&2
  echo "    export JIRA_MCP_URL=https://redhat.atlassian.net" >&2
  echo "    export JIRA_MCP_EMAIL=you@redhat.com" >&2
  echo "    export JIRA_MCP_TOKEN=<atlassian-api-token>" >&2
  echo "  Example: $EXAMPLE" >&2
  echo "" >&2
fi

# Marker for preflight + agents
python3 -c "
import json
from datetime import datetime, timezone
from pathlib import Path
p = Path('$WS') / 'mcp-ready.json'
p.write_text(json.dumps({
    'redhat_jira': True,
    'rest_fallback': $REST_AVAILABLE,
    'jira_mcp_url': '$JIRA_MCP_URL',
    'jira_mcp_email': '$JIRA_MCP_EMAIL',
    'checked_at': datetime.now(timezone.utc).isoformat(),
}, indent=2) + '\n')
"

"$ROOT/.claude/framework/lib/log_run.sh" INFO "setup_mcp: redhat-jira env checked rest_fallback=$REST_AVAILABLE url=$JIRA_MCP_URL" 2>/dev/null || true

echo "setup_mcp: redhat-jira MCP ready (REST fallback: $REST_AVAILABLE)"
echo "setup_mcp: enable 'redhat-jira' + GitHub MCP in Claude Code (see $EXAMPLE)"
if [[ "$REST_AVAILABLE" == "True" ]]; then
  echo "setup_mcp: source $MCP_ENV for terminal discovery"
fi
