# https://issues.redhat.com/browse/OCPBUGS-56015
# we are applying this w/a for every client cluster

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocs-client-operator-2
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - update
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - update
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicationclasses
  verbs:
  - update
- apiGroups:
  - groupsnapshot.storage.k8s.io
  resources:
  - volumegroupsnapshotclasses
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocs-provider-server-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocs-client-operator-2
subjects:
- kind: ServiceAccount
  name: ocs-client-operator-controller-manager
  namespace: openshift-storage
