apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-override
  namespace: openshift-storage
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
