apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-disk-{{ hostname }}
  labels:
    kubernetes.io/hostname: "{{ hostname }}"
spec:
  capacity:
    storage: "{{ storage_size | default('250Gi') }}"
  local:
    path: "{{ disk_path }}"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localblock
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "{{ hostname }}"
