"""
Claude-powered code reviewer for Provider/Client patterns.

Uses Claude API to provide intelligent, context-aware code review suggestions
based on detected pattern violations.

Signed-off-by: Claude Sonnet 4.5 <noreply@anthropic.com>
"""

import os
from typing import List, Optional
from dataclasses import dataclass

try:
    from anthropic import Anthropic
except ImportError:
    Anthropic = None

from tools.code_review.provider_client.analyzers.provider_client_analyzer import Finding


@dataclass
class ReviewComment:
    """A review comment generated by Claude"""

    file_path: str
    line_number: int
    body: str  # Markdown-formatted comment
    severity: str  # 'error', 'warning', 'info'


class ClaudeReviewer:
    """Claude-powered intelligent code reviewer"""

    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize Claude reviewer.

        Args:
            api_key: Anthropic API key (defaults to ANTHROPIC_API_KEY env var)
        """
        if Anthropic is None:
            raise ImportError(
                "anthropic package not installed. "
                "Install with: pip install anthropic"
            )

        self.api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
        if not self.api_key:
            raise ValueError(
                "ANTHROPIC_API_KEY environment variable or api_key parameter required"
            )

        self.client = Anthropic(api_key=self.api_key)
        self.model = "claude-sonnet-4-5@20250929"

    def review_findings(
        self, findings: List[Finding], context: Optional[str] = None
    ) -> List[ReviewComment]:
        """
        Get intelligent review comments from Claude for detected findings.

        Args:
            findings: List of pattern violations detected
            context: Optional additional context (e.g., PR description)

        Returns:
            List of review comments with Claude's suggestions
        """
        if not findings:
            return []

        # Group findings by file
        findings_by_file = {}
        for finding in findings:
            if finding.file_path not in findings_by_file:
                findings_by_file[finding.file_path] = []
            findings_by_file[finding.file_path].append(finding)

        comments = []

        # Review each file
        for file_path, file_findings in findings_by_file.items():
            file_comments = self._review_file_findings(
                file_path, file_findings, context
            )
            comments.extend(file_comments)

        return comments

    def _review_file_findings(
        self, file_path: str, findings: List[Finding], context: Optional[str]
    ) -> List[ReviewComment]:
        """Review findings for a single file"""

        # Build prompt for Claude
        prompt = self._build_review_prompt(file_path, findings, context)

        try:
            # Call Claude API
            response = self.client.messages.create(
                model=self.model,
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )

            # Parse response into comments
            comments = self._parse_claude_response(
                response.content[0].text, file_path, findings
            )

            return comments

        except Exception as e:
            # Fallback to basic comments if Claude API fails
            return self._generate_fallback_comments(findings)

    def _build_review_prompt(
        self, file_path: str, findings: List[Finding], context: Optional[str]
    ) -> str:
        """Build the prompt to send to Claude"""

        prompt_parts = [
            "You are a code reviewer for the ocs-ci testing framework.",
            "Your role is to review Provider/Client pattern violations and provide helpful, actionable feedback.",
            "",
            "# Context",
            "ocs-ci is a pytest-based testing framework for OpenShift Data Foundation (ODF).",
            "It supports Provider/Client mode where:",
            "- Provider cluster hosts storage services",
            "- Client clusters consume storage from Provider",
            "- Code must use `RunWithProviderConfigContextIfAvailable()` context manager when accessing Provider resources",
            "- Tests accessing Provider should use `@runs_on_provider` marker",
            "",
        ]

        if context:
            prompt_parts.extend(["# Additional Context", context, ""])

        prompt_parts.extend(
            [
                f"# File: {file_path}",
                "",
                "# Detected Issues",
                "",
            ]
        )

        # Add each finding
        for i, finding in enumerate(findings, 1):
            prompt_parts.extend(
                [
                    f"## Issue {i}",
                    f"- **Line:** {finding.line_number}",
                    f"- **Severity:** {finding.severity}",
                    f"- **Rule:** {finding.rule}",
                    f"- **Message:** {finding.message}",
                ]
            )
            if finding.code_snippet:
                prompt_parts.extend(
                    [
                        f"- **Code:**",
                        f"  ```python",
                        f"  {finding.code_snippet}",
                        f"  ```",
                    ]
                )
            prompt_parts.append("")

        prompt_parts.extend(
            [
                "# Your Task",
                "",
                "For each issue above, provide a **concise, actionable review comment** in this exact JSON format:",
                "",
                "```json",
                "[",
                "  {",
                '    "line": 14,',
                '    "severity": "error",',
                '    "comment": "This function calls `get_provider_address()` without proper context. Wrap it in:\\n\\n```python\\nwith config.RunWithProviderConfigContextIfAvailable():\\n    address = get_provider_address()\\n```\\n\\nAlternatively, add `@runs_on_provider` decorator if this entire test requires Provider access."',
                "  }",
                "]",
                "```",
                "",
                "Guidelines:",
                "- Be specific and reference the actual code",
                "- Include code snippets showing the fix (use markdown code blocks)",
                "- Explain WHY the pattern is needed (1 sentence)",
                "- Keep comments under 300 words",
                "- Use friendly, helpful tone",
                "- Return ONLY the JSON array, no other text",
            ]
        )

        return "\n".join(prompt_parts)

    def _parse_claude_response(
        self, response_text: str, file_path: str, findings: List[Finding]
    ) -> List[ReviewComment]:
        """Parse Claude's response into ReviewComment objects"""
        import json
        import re

        comments = []

        try:
            # Extract JSON from response (may be wrapped in markdown code blocks)
            json_match = re.search(
                r"```(?:json)?\s*(\[.*?\])\s*```", response_text, re.DOTALL
            )
            if json_match:
                json_text = json_match.group(1)
            else:
                # Try to parse entire response as JSON
                json_text = response_text.strip()

            parsed = json.loads(json_text)

            for item in parsed:
                comments.append(
                    ReviewComment(
                        file_path=file_path,
                        line_number=item["line"],
                        body=item["comment"],
                        severity=item.get("severity", "error"),
                    )
                )

        except (json.JSONDecodeError, KeyError, TypeError) as e:
            # Fallback: create one comment with Claude's full response
            if findings:
                comments.append(
                    ReviewComment(
                        file_path=file_path,
                        line_number=findings[0].line_number,
                        body=f"**Claude Review:**\n\n{response_text}",
                        severity=findings[0].severity,
                    )
                )

        return comments

    def _generate_fallback_comments(
        self, findings: List[Finding]
    ) -> List[ReviewComment]:
        """Generate basic comments if Claude API fails"""
        comments = []

        for finding in findings:
            body_parts = [
                f"**{finding.severity.upper()}:** {finding.message}",
                "",
            ]

            if finding.code_snippet:
                body_parts.extend(
                    [
                        "```python",
                        finding.code_snippet,
                        "```",
                        "",
                    ]
                )

            if finding.suggestion:
                body_parts.extend(["**Suggestion:**", "", finding.suggestion])

            comments.append(
                ReviewComment(
                    file_path=finding.file_path,
                    line_number=finding.line_number,
                    body="\n".join(body_parts),
                    severity=finding.severity,
                )
            )

        return comments


def format_review_comments(comments: List[ReviewComment]) -> str:
    """Format review comments for display"""
    if not comments:
        return "✓ No review comments"

    output = []
    output.append(f"\n📝 Claude Review ({len(comments)} comment(s)):\n")

    for i, comment in enumerate(comments, 1):
        output.append(f"{i}. {comment.file_path}:{comment.line_number}")
        output.append(f"   [{comment.severity.upper()}]")
        output.append("")

        # Indent comment body
        for line in comment.body.split("\n"):
            output.append(f"   {line}")
        output.append("")

    return "\n".join(output)
