
apiVersion: batch/v1
kind: Job
metadata:
  name: fill-pool-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: fill-pool
    spec:
      restartPolicy: Never
      containers:
      - name: filler
        # fedora:fio provides GNU dd and fio. FillPoolJob.create overrides command.
        image: quay.io/ocsci/fedora:fio
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - echo "Filling PVC..."
        env:
        - name: BLOCK_SIZE
          value: "4M"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
          - name: volume
            mountPath: /mnt/fill
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: fill-pool-pvc
