apiVersion: odf.isf.ibm.com/v1
kind: OdfCluster
metadata:
  name: odfcluster
  namespace: ibm-spectrum-fusion-ns
spec:
  autoScaleUp: true
  allowRemoteStorageConsumers: true
  creator: CreatedByFusion
  encryption:
    clusterWide: false
    keyManagementService:
      enable: false
  localVolumeSetSpec:
    deviceTypes:
      - disk
      - part
    diskType: SSD
  externalStorage: {}
  storageClient:
    enable: true
  storageNodes: []
  taintNode: false
