import logging

from ocs_ci.framework import config
from ocs_ci.framework.pytest_customization.marks import (
    tier2,
    red_squad,
    mcg,
    runs_on_provider,
    pre_upgrade,
    post_upgrade,
)
from ocs_ci.helpers.helpers import (
    get_noobaa_db_credentials_from_secret,
    setup_pod_directories,
)
from ocs_ci.ocs import constants
from ocs_ci.ocs.bucket_utils import (
    sync_object_directory,
    verify_s3_object_integrity,
    write_random_objects_in_pod,
)
from ocs_ci.ocs.exceptions import CommandFailed
from ocs_ci.ocs.ocp import OCP
from ocs_ci.utility.retry import retry
from ocs_ci.utility.utils import get_primary_nb_db_pod, get_secondary_nb_db_pod

logger = logging.getLogger(__name__)

# pytest cache keys used to carry state from the pre-upgrade test to the
# post-upgrade test. The two phases run as separate tests within the SAME pytest
# session (the upgrade test is ordered between them), and the pytest cache is the
# idiomatic way to persist JSON-serializable values across them.
CACHE_KEY_BUCKET = "noobaa_db_tls/pre_upgrade_bucket"
CACHE_KEY_OBJECTS = "noobaa_db_tls/pre_upgrade_objects"
CACHE_KEY_ORIGIN_DIR = "noobaa_db_tls/pre_upgrade_origin_dir"


def get_noobaa_container_envs():
    """
    Collect the environment variable definitions from the NooBaa core and both
    NooBaa DB (CNPG primary and secondary) containers.

    Returns:
        dict: Mapping of a human readable source name to its list of env var
            definitions (each a dict with ``name`` and either ``value`` or
            ``valueFrom``).

    """
    core_env = (
        OCP(
            kind=constants.STATEFULSET,
            namespace=config.ENV_DATA["cluster_namespace"],
            resource_name=constants.NOOBAA_CORE_STATEFULSET,
        )
        .get()["spec"]["template"]["spec"]["containers"][0]
        .get("env", [])
    )
    db_primary_env = (
        get_primary_nb_db_pod().get()["spec"]["containers"][0].get("env", [])
    )
    db_secondary_env = (
        get_secondary_nb_db_pod().get()["spec"]["containers"][0].get("env", [])
    )
    return {
        constants.NOOBAA_CORE_STATEFULSET: core_env,
        "noobaa-db-cnpg-primary": db_primary_env,
        "noobaa-db-cnpg-secondary": db_secondary_env,
    }


def verify_cnpg_tls_secrets():
    """
    Identify the CNPG-generated cert secrets and check they exist without any
    manual cert creation. CNPG auto-generates them, so each must have the
    expected type and key material and be owned by the CNPG Cluster CR. Note the
    CA secret is Opaque (ca.crt/ca.key) while the server and replication secrets
    are kubernetes.io/tls (tls.crt/tls.key).

    Returns:
        bool: True if all expected CNPG cert secrets exist with the correct
            type/keys and are owned by the CNPG Cluster, False otherwise.

    """
    namespace = config.ENV_DATA["cluster_namespace"]
    secret_ocp = OCP(kind=constants.SECRET, namespace=namespace)
    logger.info(
        "Validating cert secrets of the CNPG cluster "
        f"'{constants.NB_DB_CNPG_CLUSTER_NAME}' in namespace '{namespace}'"
    )
    valid = True
    for name, expected in constants.NB_DB_CNPG_TLS_SECRETS.items():
        secret = secret_ocp.get(resource_name=name, dont_raise=True)
        if secret is None:
            logger.error(
                f"Expected CNPG cert secret '{name}' does not exist; CNPG should "
                "have created it automatically (no manual cert creation)"
            )
            valid = False
            continue

        secret_type = secret.get("type")
        if secret_type != expected["type"]:
            logger.error(
                f"CNPG cert secret '{name}' has type '{secret_type}', "
                f"expected '{expected['type']}'"
            )
            valid = False

        data = secret.get("data", {})
        missing_keys = [key for key in expected["keys"] if key not in data]
        if missing_keys:
            logger.error(
                f"CNPG cert secret '{name}' is missing key material {missing_keys}; "
                f"keys present = {sorted(data)}"
            )
            valid = False

        # Confirm the secret was generated by the CNPG operator (owned by the
        # CNPG Cluster CR) rather than created manually.
        owner_kinds = [
            ref.get("kind") for ref in secret["metadata"].get("ownerReferences", [])
        ]
        if "Cluster" not in owner_kinds:
            logger.error(
                f"CNPG cert secret '{name}' is not owned by a CNPG Cluster "
                f"(ownerReferences kinds: {owner_kinds}); it may have been "
                "created manually"
            )
            valid = False
        else:
            logger.info(
                f"CNPG cert secret '{name}' OK "
                f"(type={secret_type}, keys={sorted(data)})"
            )
    if valid:
        logger.info(
            "All expected CNPG cert secrets exist with the correct type/keys and "
            "are owned by the CNPG Cluster (auto-generated, no manual certs)"
        )
    return valid


def verify_postgres_ssl_required():
    """
    Check whether the NooBaa core pod is configured to require PostgreSQL TLS.
    The noobaa-operator sets POSTGRES_SSL_REQUIRED=true (and
    POSTGRES_SSL_UNAUTHORIZED=true) when CNPG TLS is enabled.

    Returns:
        bool: True if POSTGRES_SSL_REQUIRED is set and enabled on the NooBaa
            core pod, False otherwise.

    """
    core_env = get_noobaa_container_envs()[constants.NOOBAA_CORE_STATEFULSET]
    core_env_map = {env["name"]: env.get("value") for env in core_env}
    ssl_required = core_env_map.get(constants.POSTGRES_SSL_REQUIRED_ENV)
    logger.info(
        f"NooBaa core {constants.POSTGRES_SSL_REQUIRED_ENV}={ssl_required}, "
        f"{constants.POSTGRES_SSL_UNAUTHORIZED_ENV}="
        f"{core_env_map.get(constants.POSTGRES_SSL_UNAUTHORIZED_ENV)}"
    )
    if constants.POSTGRES_SSL_REQUIRED_ENV not in core_env_map:
        logger.error(
            f"{constants.POSTGRES_SSL_REQUIRED_ENV} env var is not set on the "
            f"NooBaa core container; env vars present: {sorted(core_env_map)}"
        )
        return False
    if str(ssl_required).lower() not in ("true", "1"):
        logger.error(
            f"{constants.POSTGRES_SSL_REQUIRED_ENV} is not enabled on the NooBaa "
            f"core pod (value={ssl_required})"
        )
        return False
    return True


def verify_encrypted_db_connection(host=constants.CNPG_READ_WRITE_HOST):
    """
    Check whether the connection to the NooBaa DB is actually encrypted. Connect
    over TCP to the given service (read-write or read-only) with sslmode=require
    (a local unix-socket connection is never encrypted, and require makes the
    connection fail rather than silently fall back to plaintext if TLS is
    unavailable). ssl_is_used() needs the optional sslinfo extension (not
    installed), so use the built-in pg_stat_ssl view scoped to our own backend.

    Args:
        host (str): The NooBaa DB service to connect to (defaults to the CNPG
            read-write service). Pass constants.CNPG_READ_ONLY_HOST to validate
            the read-only replica endpoint.

    Returns:
        bool: True if the current backend connection is using TLS
            (pg_stat_ssl.ssl == 't'), False otherwise.

    """
    db_user, db_password = get_noobaa_db_credentials_from_secret()
    nb_db_pod = get_primary_nb_db_pod()
    ssl_query = "SELECT ssl FROM pg_stat_ssl WHERE pid = pg_backend_pid();"
    psql_cmd = (
        f"PGPASSWORD='{db_password}' psql "
        f"'host={host} dbname=nbcore "
        f"user={db_user} sslmode=require' "
        f"-tAc '{ssl_query}'"
    )
    # With sslmode=require, a DB that does not serve TLS makes psql fail to
    # connect (non-zero exit), which exec_sh_cmd_on_pod surfaces as a
    # CommandFailed. Treat that as "TLS not in use" and return False so the
    # helper keeps its boolean contract instead of erroring the test.
    try:
        ssl_used = (
            nb_db_pod.exec_sh_cmd_on_pod(command=psql_cmd, secrets=[db_password])
            .strip()
            .lower()
        )
    except CommandFailed as ex:
        logger.error(f"Failed to query pg_stat_ssl over TLS on host '{host}': {ex}")
        return False
    logger.info(
        f"pg_stat_ssl.ssl for the current backend on host '{host}' "
        f"returned: {ssl_used}"
    )
    if ssl_used != "t":
        logger.error(
            f"Encrypted (TLS) connection to the NooBaa DB on host '{host}' is "
            f"not in use; pg_stat_ssl.ssl returned '{ssl_used}' instead of 't'"
        )
        return False
    return True


def verify_no_tls_key_material_in_env():
    """
    Check that no TLS key material is exposed via env vars. The certs must be
    mounted from secrets (referenced via valueFrom.secretKeyRef or as volume
    mounts), never inlined as literal PEM values in the env.

    Returns:
        bool: True if no raw TLS key/cert material is found in the NooBaa core
            or DB container env vars, False otherwise.

    """
    # PEM markers that would indicate raw TLS key/cert material in an env var
    pem_markers = (
        "BEGIN PRIVATE KEY",
        "BEGIN RSA PRIVATE KEY",
        "BEGIN EC PRIVATE KEY",
        "BEGIN ENCRYPTED PRIVATE KEY",
        "BEGIN CERTIFICATE",
    )
    no_key_material = True
    for source, env_vars in get_noobaa_container_envs().items():
        for env in env_vars:
            value = env.get("value")
            if not value:
                continue
            for marker in pem_markers:
                if marker in value:
                    logger.error(
                        f"TLS key/cert material leaked into env var "
                        f"'{env['name']}' on {source} (found '{marker}')"
                    )
                    no_key_material = False
    if no_key_material:
        logger.info(
            "No raw TLS key/cert material is exposed in the NooBaa core or DB "
            "container environment variables"
        )
    return no_key_material


@mcg
@red_squad
@runs_on_provider
class TestNoobaaDbTLS:
    """
    Verify that the NooBaa DB (PostgreSQL managed by the CloudNativePG operator)
    serves connections over TLS using certificates that CNPG generates
    automatically, without any manual certificate creation.
    """

    @tier2
    def test_noobaa_db_cnpg_tls(self):
        """
        Verify NooBaa DB TLS on an already-deployed cluster:

        1. Get secrets and identify the cert secrets created by CNPG.
        2. Verify the cert secrets exist without any manual cert creation.
        3. Verify the NooBaa core pod requires PostgreSQL TLS
           (POSTGRES_SSL_REQUIRED env).
        4. Verify the connection is encrypted (pg_stat_ssl / ssl_is_used == t)
           on both the read-write and read-only DB service endpoints.
        5. Verify there is no TLS key material exposed in env vars.
        """
        assert verify_cnpg_tls_secrets(), (
            "CNPG cert secrets validation failed; see logs for the offending "
            "secret(s)"
        )
        assert (
            verify_postgres_ssl_required()
        ), "NooBaa core does not require PostgreSQL TLS (POSTGRES_SSL_REQUIRED)"
        assert verify_encrypted_db_connection(
            constants.CNPG_READ_WRITE_HOST
        ), "NooBaa DB read-write connection is not encrypted (TLS not in use)"
        assert verify_encrypted_db_connection(
            constants.CNPG_READ_ONLY_HOST
        ), "NooBaa DB read-only connection is not encrypted (TLS not in use)"
        assert (
            verify_no_tls_key_material_in_env()
        ), "TLS key/cert material is exposed in NooBaa container env vars"

    @pre_upgrade
    def test_noobaa_db_tls_fill_bucket_before_upgrade(
        self, request, mcg_obj_session, awscli_pod_session, bucket_factory_session
    ):
        """
        Pre-upgrade (ODF N-1, internal NooBaa without TLS):

        Create a bucket and upload objects; the uploaded objects act as the
        checksum baseline for post-upgrade comparison.
        """
        bucket = bucket_factory_session(1)[0]
        mcg_bucket_path = f"s3://{bucket.name}"

        # Create the origin dir under the test name on the awscli pod. Call
        # setup_pod_directories directly (not the test_directory_setup fixture)
        # so the baseline objects survive the upgrade without being cleaned up.
        origin_dir = setup_pod_directories(awscli_pod_session, ["origin"])[0]
        pre_upgrade_objects = write_random_objects_in_pod(
            awscli_pod_session, origin_dir, amount=5
        )
        assert pre_upgrade_objects, "No objects generated in the pre-upgrade phase"

        logger.info(f"Uploading pre-upgrade objects to bucket '{bucket.name}'")
        retry(CommandFailed, tries=3, delay=10)(sync_object_directory)(
            awscli_pod_session, origin_dir, mcg_bucket_path, mcg_obj_session
        )

        # Persist the pre-upgrade state for the post-upgrade test via the pytest
        # cache (values are JSON-serializable).
        request.config.cache.set(CACHE_KEY_BUCKET, bucket.name)
        request.config.cache.set(CACHE_KEY_OBJECTS, pre_upgrade_objects)
        request.config.cache.set(CACHE_KEY_ORIGIN_DIR, origin_dir)
        logger.info(
            f"Recorded {len(pre_upgrade_objects)} pre-upgrade objects in "
            f"bucket '{bucket.name}' as the checksum baseline"
        )

    @post_upgrade
    def test_noobaa_db_tls_after_upgrade(
        self, request, mcg_obj_session, awscli_pod_session
    ):
        """
        Post-upgrade (ODF 5.0, TLS auto-enabled by the operator):

        1. Verify the CNPG TLS cert secrets were created.
        2. Verify POSTGRES_SSL_REQUIRED=true and the DB connection is encrypted
           (SELECT ssl ... / ssl_is_used == t), with no TLS key material in env.
           TLS being required now, with no action taken between the two phases,
           shows the operator handled the Prefer -> Require transition itself.
        3. Re-download all pre-upgrade objects and compare checksums against the
           pre-upgrade baseline.
        """
        pre_upgrade_bucket = request.config.cache.get(CACHE_KEY_BUCKET, None)
        pre_upgrade_objects = request.config.cache.get(CACHE_KEY_OBJECTS, None)
        origin_dir = request.config.cache.get(CACHE_KEY_ORIGIN_DIR, None)
        assert (
            pre_upgrade_bucket and pre_upgrade_objects and origin_dir
        ), "No pre-upgrade state recorded; the pre-upgrade phase did not run"

        # Steps 1-2: full TLS validation now that the cluster is upgraded. The
        # operator enabled Require mode on its own (no manual action between the
        # two phases), which verify_postgres_ssl_required confirms.
        assert verify_cnpg_tls_secrets(), (
            "CNPG cert secrets validation failed after upgrade; see logs for the "
            "offending secret(s)"
        )
        assert verify_postgres_ssl_required(), (
            "NooBaa core does not require PostgreSQL TLS after upgrade "
            "(operator did not enable Require mode)"
        )
        assert verify_encrypted_db_connection(constants.CNPG_READ_WRITE_HOST), (
            "NooBaa DB read-write connection is not encrypted after upgrade "
            "(TLS not in use)"
        )
        assert verify_encrypted_db_connection(constants.CNPG_READ_ONLY_HOST), (
            "NooBaa DB read-only connection is not encrypted after upgrade "
            "(TLS not in use)"
        )
        assert (
            verify_no_tls_key_material_in_env()
        ), "TLS key/cert material is exposed in NooBaa container env vars after upgrade"

        # Step 3: re-download the pre-upgrade objects and compare checksums
        mcg_bucket_path = f"s3://{pre_upgrade_bucket}"
        result_dir = setup_pod_directories(awscli_pod_session, ["result"])[0]
        logger.info(
            f"Re-downloading pre-upgrade objects from bucket '{pre_upgrade_bucket}'"
        )
        retry(CommandFailed, tries=3, delay=10)(sync_object_directory)(
            awscli_pod_session, mcg_bucket_path, result_dir, mcg_obj_session
        )
        for obj in pre_upgrade_objects:
            assert verify_s3_object_integrity(
                original_object_path=f"{origin_dir}/{obj}",
                result_object_path=f"{result_dir}/{obj}",
                awscli_pod=awscli_pod_session,
            ), (
                f"Checksum mismatch for object '{obj}' between the pre-upgrade "
                "baseline and the post-upgrade download"
            )
        logger.info(
            f"All {len(pre_upgrade_objects)} pre-upgrade objects match their "
            "checksum baseline after the upgrade"
        )
