FROM registry.redhat.io/ubi8/ubi

# Based on https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a

# Use this dockerfile to create ocs-ci infra and run test based on argument

# Configure k8s repository to install kubectl packages.
COPY k8s.repo /etc/yum.repos.d/k8s.repo

# Python package installation.
RUN INSTALL_PKGS="python38 python38-devel python38-setuptools python38-pip \
      libffi-devel libcurl-devel openssl-devel libxslt-devel libxml2-devel libtool-ltdl enchant glibc-langpack-en redhat-rpm-config \
      git gcc kubectl" && \
    yum -y module enable python38:3.8 && \
    yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum -y clean all --enablerepo='*' && \
    rm -rf /var/cache/yum

# Environment variables containing various file locations required by install-ocs-ci.sh script
ENV OCSCI_INSTALL_DIR=/opt/ocs-ci \
    CLUSTER_DIR=/opt/cluster

# Copy install-ocs-ci.sh script inside the container.
COPY scripts/install-ocs-ci.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/*.sh

# Install ocs-ci inside the container.
RUN install-ocs-ci.sh

# Install oc client
ADD https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz /
RUN cd /usr/local/bin && \
    tar -xvf /openshift-client-linux.tar.gz oc


# Copy kubeconfig file to the container.
RUN mkdir -p /opt/cluster/auth
COPY scripts/kubeconfig /opt/cluster/auth

# Get test_path argument
ARG TEST_PATH_ARG
ENV TEST_PATH=${TEST_PATH_ARG}

# Get ocp_version argument
ARG OCP_VERSION_ARG
ENV OCP_VERSION=${OCP_VERSION_ARG}

# Get ocs_version argument
ARG OCS_VERSION_ARG
ENV OCS_VERSION=${OCS_VERSION_ARG}

# Get pytest_marker argument
ARG MARKER_PYTEST_ARG
ENV MARKER_PYTEST=${MARKER_PYTEST_ARG}

# Copy run-ci.sh script to continer
COPY scripts/run-ci.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/*.sh
RUN run-ci.sh

CMD [ "/bin/echo", "ocsci base container" ]

ENTRYPOINT /bin/bash
