must_gather_base = {
    'noobaa/logs/openshift-storage/noobaa-core-0.log': None,
    'noobaa/logs/openshift-storage/noobaa-db-0.log': None,
    'noobaa/namespaces/openshift-storage/noobaa.io/bucketclasses/noobaa-default-bucket-class.yaml': None,
    'noobaa/namespaces/openshift-storage/noobaa.io/noobaas/noobaa.yaml': None,
    'noobaa/namespaces/openshift-storage/noobaa.io/backingstores/noobaa-default-backing-store.yaml': None,
}

must_gather_4_5 = {
    'ceph/namespaces/openshift-storage/apps.openshift.io/deploymentconfigs.yaml': None,
    'ceph/namespaces/openshift-storage/apps/daemonsets.yaml': None,
    'ceph/namespaces/openshift-storage/apps/deployments.yaml': None,
    'ceph/namespaces/openshift-storage/apps/replicasets.yaml': None,
    'ceph/namespaces/openshift-storage/apps/statefulsets.yaml': None,
    'ceph/namespaces/openshift-storage/autoscaling/horizontalpodautoscalers.yaml': None,
    'ceph/namespaces/openshift-storage/batch/cronjobs.yaml': None,
    'ceph/namespaces/openshift-storage/batch/jobs.yaml': None,
    'ceph/namespaces/openshift-storage/build.openshift.io/buildconfigs.yaml': None,
    'ceph/namespaces/openshift-storage/build.openshift.io/builds.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephblockpools/ocs-storagecluster-cephblockpool.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephclusters/ocs-storagecluster-cephcluster.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephfilesystems/ocs-storagecluster-cephfilesystem.yaml': None,
    'ceph/namespaces/openshift-storage/core/configmaps.yaml': None,
    'ceph/namespaces/openshift-storage/core/endpoints.yaml': None,
    'ceph/namespaces/openshift-storage/core/events.yaml': None,
    'ceph/namespaces/openshift-storage/core/persistentvolumeclaims.yaml': None,
    'ceph/namespaces/openshift-storage/core/pods.yaml': None,
    'ceph/namespaces/openshift-storage/core/replicationcontrollers.yaml': None,
    'ceph/namespaces/openshift-storage/core/secrets.yaml': None,
    'ceph/namespaces/openshift-storage/core/services.yaml': None,
    'ceph/namespaces/openshift-storage/image.openshift.io/imagestreams.yaml': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph-volume_raw_list': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_auth_list': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_balancer_status': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_config-key_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_config_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_crash_stat': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_device_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_df': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_fs_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_fs_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_fs_status': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/'
    'ceph_fs_subvolume_ls_ocs-storagecluster-cephfilesystem_csi': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/'
    'ceph_fs_subvolumegroup_ls_ocs-storagecluster-cephfilesystem': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_health_detail': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_mds_stat': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_mgr_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_mgr_module_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_mgr_services': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_mon_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_mon_stat': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_blacklist_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_blocked-by': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_crush_class_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_crush_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_crush_rule_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_crush_rule_ls': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_crush_show-tunables': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_crush_weight-set_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_df': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_df_tree': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_getmaxosd': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_lspools': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_numa-status': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_perf': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_pool_ls_detail': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_stat': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_tree': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_osd_utilization': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_pg_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_pg_stat': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_progress': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_progress_json': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_quorum_status': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_report': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_service_dump': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_status': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_time-sync-status': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/ceph_versions': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_auth_list_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_balancer_pool_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_balancer_status_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_config-key_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_config_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_crash_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_crash_stat_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_device_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_df_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_fs_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_fs_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_fs_status_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_fs_subvolume_ls_ocs-storagecluster-cephfilesystem_csi_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_fs_subvolumegroup_ls_ocs-storagecluster-cephfilesystem_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_health_detail_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_mds_stat_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_mgr_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_mgr_module_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_mgr_services_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_mon_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_mon_stat_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_blacklist_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_blocked-by_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_crush_class_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_crush_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_crush_rule_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_crush_rule_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_crush_show-tunables_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_crush_weight-set_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_crush_weight-set_ls_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_df_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_df_tree_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_getmaxosd_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_lspools_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_numa-status_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_perf_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_pool_ls_detail_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_stat_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_osd_tree_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/'
    'ceph_osd_utilization_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_pg_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_pg_stat_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_progress_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_progress_json_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_quorum_status_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_report_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_service_dump_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_status_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/'
    'json_output/ceph_time-sync-status_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/json_output/ceph_versions_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/must_gather_commands/pools_rbd_ocs-storagecluster-cephblockpool': None,
    'ceph/namespaces/openshift-storage/openshift-storage.yaml': None,
    'ceph/namespaces/openshift-storage/route.openshift.io/routes.yaml': None,
    'oc_output/describe_nodes': 'cpu',
    'oc_output/describe_pods_-n_openshift-storage': 'Type',
    'oc_output/get_clusterversion_-oyaml': 'kind',
    'oc_output/get_csv_-n_openshift-storage': 'ocs-operator',
    'oc_output/get_infrastructures.config_-oyaml': 'metadata:',
    'oc_output/get_nodes_--show-labels': 'NAME',
    'oc_output/get_pods_-owide_-n_openshift-storage': 'ceph-osd',
    'oc_output/get_pv': 'CAPACITY',
    'oc_output/get_pvc_--all-namespaces': 'openshift',
    'oc_output/get_sc': 'ocs-storage',
    'oc_output/get_subscription_-n_openshift-storage': 'ocs-sub',
    'storagecluster.yaml': None,
}

must_gather_4_6 = {
    'ceph/must_gather_commands/ceph-volume_raw_list': None,
    'ceph/must_gather_commands/ceph_auth_list': None,
    'ceph/must_gather_commands/ceph_balancer_status': None,
    'ceph/must_gather_commands/ceph_config-key_ls': None,
    'ceph/must_gather_commands/ceph_config_dump': None,
    'ceph/must_gather_commands/ceph_crash_stat': None,
    'ceph/must_gather_commands/ceph_device_ls': None,
    'ceph/must_gather_commands/ceph_df': None,
    'ceph/must_gather_commands/ceph_fs_dump': None,
    'ceph/must_gather_commands/ceph_fs_ls': None,
    'ceph/must_gather_commands/ceph_fs_status': None,
    'ceph/must_gather_commands/ceph_fs_subvolume_ls_ocs-storagecluster-cephfilesystem_csi': None,
    'ceph/must_gather_commands/ceph_fs_subvolumegroup_ls_ocs-storagecluster-cephfilesystem': None,
    'ceph/must_gather_commands/ceph_health_detail': None,
    'ceph/must_gather_commands/ceph_mds_stat': None,
    'ceph/must_gather_commands/ceph_mgr_dump': None,
    'ceph/must_gather_commands/ceph_mgr_module_ls': None,
    'ceph/must_gather_commands/ceph_mgr_services': None,
    'ceph/must_gather_commands/ceph_mon_dump': None,
    'ceph/must_gather_commands/ceph_mon_stat': None,
    'ceph/must_gather_commands/ceph_osd_blacklist_ls': None,
    'ceph/must_gather_commands/ceph_osd_blocked-by': None,
    'ceph/must_gather_commands/ceph_osd_crush_class_ls': None,
    'ceph/must_gather_commands/ceph_osd_crush_dump': None,
    'ceph/must_gather_commands/ceph_osd_crush_rule_dump': None,
    'ceph/must_gather_commands/ceph_osd_crush_rule_ls': None,
    'ceph/must_gather_commands/ceph_osd_crush_show-tunables': None,
    'ceph/must_gather_commands/ceph_osd_crush_weight-set_dump': None,
    'ceph/must_gather_commands/ceph_osd_df': None,
    'ceph/must_gather_commands/ceph_osd_df_tree': None,
    'ceph/must_gather_commands/ceph_osd_dump': None,
    'ceph/must_gather_commands/ceph_osd_getmaxosd': None,
    'ceph/must_gather_commands/ceph_osd_lspools': None,
    'ceph/must_gather_commands/ceph_osd_numa-status': None,
    'ceph/must_gather_commands/ceph_osd_perf': None,
    'ceph/must_gather_commands/ceph_osd_pool_ls_detail': None,
    'ceph/must_gather_commands/ceph_osd_stat': None,
    'ceph/must_gather_commands/ceph_osd_tree': None,
    'ceph/must_gather_commands/ceph_osd_utilization': None,
    'ceph/must_gather_commands/ceph_pg_dump': None,
    'ceph/must_gather_commands/ceph_pg_stat': None,
    'ceph/must_gather_commands/ceph_progress': None,
    'ceph/must_gather_commands/ceph_progress_json': None,
    'ceph/must_gather_commands/ceph_quorum_status': None,
    'ceph/must_gather_commands/ceph_report': None,
    'ceph/must_gather_commands/ceph_service_dump': None,
    'ceph/must_gather_commands/ceph_status': None,
    'ceph/must_gather_commands/ceph_time-sync-status': None,
    'ceph/must_gather_commands/ceph_versions': None,
    'ceph/must_gather_commands/pools_rbd_ocs-storagecluster-cephblockpool': None,
    'ceph/must_gather_commands_json_output/ceph_auth_list_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_balancer_pool_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_balancer_status_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_config-key_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_config_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_crash_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_crash_stat_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_device_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_df_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_fs_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_fs_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_fs_status_--format_json-pretty': None,
    'ceph_fs_subvolume_ls_ocs-storagecluster-cephfilesystem_csi_--format_json-pretty': None,
    'ceph_fs_subvolumegroup_ls_ocs-storagecluster-cephfilesystem_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_health_detail_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_mds_stat_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_mgr_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_mgr_module_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_mgr_services_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_mon_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_mon_stat_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_blacklist_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_blocked-by_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_class_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_rule_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_rule_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_show-tunables_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_weight-set_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_crush_weight-set_ls_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_df_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_df_tree_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_getmaxosd_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_lspools_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_numa-status_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_perf_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_pool_ls_detail_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_stat_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_tree_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_osd_utilization_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_pg_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_pg_stat_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_progress_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_progress_json_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_quorum_status_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_report_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_service_dump_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_status_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_time-sync-status_--format_json-pretty': None,
    'ceph/must_gather_commands_json_output/ceph_versions_--format_json-pretty': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephblockpools/ocs-storagecluster-cephblockpool.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephclusters/ocs-storagecluster-cephcluster.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephfilesystems/ocs-storagecluster-cephfilesystem.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephobjectstores/ocs-storagecluster-cephobjectstore.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephobjectstoreusers/noobaa-ceph-objectstore-user.yaml': None,
    'ceph/namespaces/openshift-storage/ceph.rook.io/cephobjectstoreusers/'
    'ocs-storagecluster-cephobjectstoreuser.yaml': None,
    'cluster-scoped-resources/config.openshift.io/clusterversions/version.yaml': None,
    'cluster-scoped-resources/config.openshift.io/infrastructures/cluster.yaml': None,
    'cluster-scoped-resources/oc_output/clusterrole': None,
    'cluster-scoped-resources/oc_output/clusterrolebinding': None,
    'cluster-scoped-resources/oc_output/clusterversion': None,
    'cluster-scoped-resources/oc_output/infrastructures.config': None,
    'cluster-scoped-resources/oc_output/pv': None,
    'cluster-scoped-resources/oc_output/sc': None,
    'cluster-scoped-resources/storage.k8s.io/storageclasses/ocs-storagecluster-ceph-rbd.yaml': None,
    'cluster-scoped-resources/storage.k8s.io/storageclasses/ocs-storagecluster-ceph-rgw.yaml': None,
    'cluster-scoped-resources/storage.k8s.io/storageclasses/ocs-storagecluster-cephfs.yaml': None,
    'cluster-scoped-resources/storage.k8s.io/storageclasses/openshift-storage.noobaa.io.yaml': None,
    'namespaces/all/namespaces/openshift-image-registry/core/persistentvolumeclaims/registry-cephfs-rwx-pvc.yaml': None,
    'namespaces/all/namespaces/openshift-monitoring/core/persistentvolumeclaims/'
    'my-alertmanager-claim-alertmanager-main-0.yaml': None,
    'namespaces/all/namespaces/openshift-monitoring/core/persistentvolumeclaims/'
    'my-alertmanager-claim-alertmanager-main-1.yaml': None,
    'namespaces/all/namespaces/openshift-monitoring/core/persistentvolumeclaims/'
    'my-alertmanager-claim-alertmanager-main-2.yaml': None,
    'namespaces/all/namespaces/openshift-monitoring/core/persistentvolumeclaims/'
    'my-prometheus-claim-prometheus-k8s-0.yaml': None,
    'namespaces/all/namespaces/openshift-monitoring/core/persistentvolumeclaims/'
    'my-prometheus-claim-prometheus-k8s-1.yaml': None,
    'namespaces/all/pvc_all_namespaces': None,
    'namespaces/openshift-storage/apps.openshift.io/deploymentconfigs.yaml': None,
    'namespaces/openshift-storage/apps/daemonsets.yaml': None,
    'namespaces/openshift-storage/apps/deployments.yaml': None,
    'namespaces/openshift-storage/apps/replicasets.yaml': None,
    'namespaces/openshift-storage/apps/statefulsets.yaml': None,
    'namespaces/openshift-storage/autoscaling/horizontalpodautoscalers.yaml': None,
    'namespaces/openshift-storage/batch/cronjobs.yaml': None,
    'namespaces/openshift-storage/batch/jobs.yaml': None,
    'namespaces/openshift-storage/build.openshift.io/buildconfigs.yaml': None,
    'namespaces/openshift-storage/build.openshift.io/builds.yaml': None,
    'namespaces/openshift-storage/core/configmaps.yaml': None,
    'namespaces/openshift-storage/core/endpoints.yaml': None,
    'namespaces/openshift-storage/core/events.yaml': None,
    'namespaces/openshift-storage/core/persistentvolumeclaims.yaml': None,
    'namespaces/openshift-storage/core/pods.yaml': None,
    'namespaces/openshift-storage/core/replicationcontrollers.yaml': None,
    'namespaces/openshift-storage/core/secrets.yaml': None,
    'namespaces/openshift-storage/core/services.yaml': None,
    'namespaces/openshift-storage/discovery.k8s.io/endpointslices.yaml': None,
    'namespaces/openshift-storage/image.openshift.io/imagestreams.yaml': None,
    'namespaces/openshift-storage/oc_output/all': 'pod/rook-ceph',
    'namespaces/openshift-storage/oc_output/csv': 'rook-ceph',
    'namespaces/openshift-storage/oc_output/events': 'Normal',
    'namespaces/openshift-storage/oc_output/installplan': 'NAME',
    'namespaces/openshift-storage/oc_output/nodes': 'CPU Limits',
    'namespaces/openshift-storage/oc_output/nodes_--show-labels': 'memory',
    'namespaces/openshift-storage/oc_output/pods': 'Namespace:',
    'namespaces/openshift-storage/oc_output/pods_-owide': 'rook-ceph-osd',
    'namespaces/openshift-storage/oc_output/role': 'ocs-operator',
    'namespaces/openshift-storage/oc_output/rolebinding': 'ocs-operator',
    'namespaces/openshift-storage/oc_output/storagecluster': 'Kind:',
    'namespaces/openshift-storage/oc_output/storagecluster.yaml': None,
    'namespaces/openshift-storage/oc_output/subscription': 'PACKAGE',
    'namespaces/openshift-storage/openshift-storage.yaml': None,
    'namespaces/openshift-storage/route.openshift.io/routes.yaml': None,
}

must_gather_version = {
    4.5: must_gather_4_5,
    4.6: must_gather_4_6
}
