apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: hyperconverged-catalogsource
  namespace: openshift-marketplace
spec:
  # Image is set in ocs_ci.deployment.hyperconverged.create_catalog_source
  # OCP 4.x: quay.io/kubevirt/hyperconverged-cluster-index:<x.y>.0-unstable
  # OCP 5.x: quay.io/kubevirt/hyperconverged-cluster-index:<latest-stable>
  image: ''
  sourceType: grpc
